<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 * Admin Category Controller
 * 
 * Handles category management for the admin dashboard.
 * 
 * Features:
 * - CRUD operations for categories
 * - Validation for category data
 * - Automatic slug generation
 * - Protected by admin middleware
 * - Eager loading for performance
 * 
 * @package App\Http\Controllers\Admin
 */
class CategoryController extends Controller
{
    /**
     * Display a listing of categories.
     * 
     * Shows all categories with comic counts for the admin dashboard.
     * Uses eager loading to prevent N+1 queries.
     * 
     * @return View
     */
    public function index(): View
    {
        $this->authorizeAccess();

        // Eager load comic counts to prevent N+1 queries
        $categories = Category::withComicCount()
            ->orderBy('name')
            ->paginate(20);

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new category.
     * 
     * @return View
     */
    public function create(): View
    {
        $this->authorizeAccess();

        return view('admin.categories.create');
    }

    /**
     * Store a newly created category in storage.
     * 
     * Validates input and creates the category.
     * Slug is automatically generated by the model.
     * 
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $this->authorizeAccess();

        // Validate category data
        $validated = $request->validate([
            'name' => 'required|string|max:255|unique:categories,name',
            'description' => 'nullable|string|max:1000',
        ]);

        // Create category (slug is auto-generated by model)
        Category::create($validated);

        return redirect()
            ->route('admin.categories.index')
            ->with('success', 'Category created successfully.');
    }

    /**
     * Show the form for editing the specified category.
     * 
     * @param Category $category
     * @return View
     */
    public function edit(Category $category): View
    {
        $this->authorizeAccess();

        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified category in storage.
     * 
     * Validates input and updates the category.
     * Slug is automatically regenerated if name changes.
     * 
     * @param Request $request
     * @param Category $category
     * @return RedirectResponse
     */
    public function update(Request $request, Category $category): RedirectResponse
    {
        $this->authorizeAccess();

        // Validate category data
        $validated = $request->validate([
            'name' => 'required|string|max:255|unique:categories,name,' . $category->id,
            'description' => 'nullable|string|max:1000',
        ]);

        // Update category (slug is auto-updated by model if name changes)
        $category->update($validated);

        return redirect()
            ->route('admin.categories.index')
            ->with('success', 'Category updated successfully.');
    }

    /**
     * Remove the specified category from storage.
     * 
     * Deletes the category. Related pivot table entries are
     * automatically deleted due to cascade delete in migration.
     * 
     * @param Category $category
     * @return RedirectResponse
     */
    public function destroy(Category $category): RedirectResponse
    {
        $this->authorizeAccess();

        // Delete category (cascade delete handles pivot table)
        $category->delete();

        return redirect()
            ->route('admin.categories.index')
            ->with('success', 'Category deleted successfully.');
    }

    /**
     * Authorize access - only super admins can manage categories.
     * 
     * @return void
     */
    protected function authorizeAccess(): void
    {
        if (!auth()->check() || !auth()->user()->isSuperAdmin()) {
            abort(403, 'Unauthorized access');
        }
    }
}
